[variables]
NODE_OPTIONS = "--max-old-space-size=4096"
NEXT_TELEMETRY_DISABLED = "1"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
aptPkgs = [
  "nodejs_22",
  "qpdf",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgbm1",
  "libasound2t64",
  "libpangocairo-1.0-0",
  "libxss1",
  "libgtk-3-0",
  "libxshmfence1",
  "libglu1"
]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"